hw10_app/hw10_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("quotes_app.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
]

hw10_app/quotes_app/urls.py
from django.urls import path

from . import views

app_name = "quotes_app"

urlpatterns = [
    path("", views.index, name="main"),
    path("quotes/add_author", views.add_author, name="add_author"),
    path("quotes/add_quot", views.add_quot, name="add_quot"),
    path("quotes/author_page", views.author_page, name="author_page"),
    path("quotes/tags_search", views.tags_search, name="tags_search"),
    path("quotes/scrap_data", views.scrap_data, name="scrap_data"),
    path("quotes/tag_list", views.get_most_used_tags, name="tag_list"),

]

hw10_app/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name="signup"),
    path("signin/",
         LoginView.as_view(template_name="users/signin.html", form_class=LoginForm, redirect_authenticated_user=True),
         name="signin"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw10_app/users/models.py
from django.db import models

# Create your models here.

hw10_app/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=25, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=25, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=160, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=12, min_length=8, required=True,
                         widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

hw10_app/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse_lazy

from .forms import RegisterForm


# Create your views here.


class RegisterView(View):
    template_name = "users/signup.html"
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes_app:main")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо {username}. Ваш акаунт успішно створено")
            return redirect(to="users:signin")

        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

hw10_app/users/templates/users/logout.html
{% extends "quotes_app/base.html" %}

{% block content %}

<div class="container mt-3 text-center">
    <h2 class="mb-3">Повертайтесь будь ласка</h2>
    <p>Redirecting in 3 seconds...</p>
</div>

<script type="text/javascript">
    setTimeout(function() {
        window.location.href = "{% url 'quotes_app:main' %}";
    }, 3000);

</script>

{% endblock %}

hw10_app/users/templates/users/password_reset.html
{% extends "quotes_app/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw10_app/users/templates/users/password_reset_complete.html
{% extends "quotes_app/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw10_app/users/templates/users/password_reset_confirm.html
{% extends "quotes_app/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw10_app/users/templates/users/password_reset_done.html
{% extends "quotes_app/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw10_app/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw10_app/users/templates/users/signin.html
{% extends "quotes_app/base.html" %}

{% block content %}

<div class="container mt-3 text-center">
    <h2 class="mb-3">Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }} </span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
            <a href="{% url 'users:signup' %}" class="btn btn-success">Sign Up</a>
        </div>
        <div class="small text-center">
         <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
    </form>

</div>

{% endblock %}

hw10_app/users/templates/users/signup.html
{% extends "quotes_app/base.html" %}

{% block content %}

<div class="container mt-3 text-center">
    <h2>Registration User</h2>
    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">First name
                {{ form.first_name }}
            </label>
            <span>{{form.errors.first_name}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Last name
                {{ form.last_name }}
            </label>
            <span>{{form.errors.last_name}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
            <a href="{% url 'users:signin' %}" class="btn btn-success">Login</a>
        </div>
    </form>

</div>

{% endblock %}