hw10_app/hw10_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("quotes_app.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
]

hw10_app/quotes_app/urls.py
from django.urls import path

from . import views

app_name = "quotes_app"

urlpatterns = [
    path("", views.index, name="main"),
    path("quotes/add_author", views.add_author, name="add_author"),
    path("quotes/add_quot", views.add_quot, name="add_quot"),
    path("quotes/author_page", views.author_page, name="author_page"),
    path("quotes/tags_search", views.tags_search, name="tags_search"),
    path("quotes/scrap_data", views.scrap_data, name="scrap_data"),
    path("quotes/tag_list", views.get_most_used_tags, name="tag_list"),

]

hw10_app/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name="signup"),
    path("signin/",
         LoginView.as_view(template_name="users/signin.html", form_class=LoginForm, redirect_authenticated_user=True),
         name="signin"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw10_app/quotes_app/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=200)
    born_date = models.CharField(max_length=120)
    born_location = models.CharField(max_length=120)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=40, null=False)

    def __str__(self):
        return self.name


class Quot(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    quot = models.TextField()
    tags = models.ManyToManyField(Tag)
    creation_date = models.DateTimeField(auto_now_add=True)

hw10_app/quotes_app/forms.py
from django.forms import CharField, TextInput, Textarea, ModelForm, ModelChoiceField, Select

from .models import Author, Quot


class AuthorForm(ModelForm):
    fullname = CharField(
        max_length=200,
        required=True,
        widget=TextInput(attrs={"class": "form-control"})
    )

    born_date = CharField(
        max_length=120,
        required=True,
        widget=TextInput(attrs={"class": "form-control"})
    )

    born_location = CharField(
        max_length=120, required=True,
        widget=TextInput(attrs={"class": "form-control"})
    )

    description = CharField(
        required=True,
        widget=Textarea(attrs={"class": "form-control"})
    )

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuotForm(ModelForm):
    author_choices = Author.objects.all()

    author = ModelChoiceField(
        label="Author",
        queryset=author_choices,
        to_field_name="fullname",
        empty_label="Choose an author below",
        required=True,
        widget=Select(attrs={"class": "form-control"})
    )

    quot = CharField(
        label="Quot",
        required=True,
        widget=Textarea(attrs={"class": "form-control"})
    )

    tags = CharField(
        label="Tags",
        required=True,
        widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Quot
        fields = ["author", "quot", "tags"]

hw10_app/quotes_app/views.py
from django.contrib.auth.decorators import login_required
from django.db import connection
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import AuthorForm, QuotForm
from .models import Quot, Author, Tag
from .scraping import make_scraping


def scrap_data(request):
    if request.method == "GET":

        result_dict = make_scraping()

        saved_authors = {}

        for author_dict in result_dict["authors"]:

            author = Author.objects.filter(fullname=author_dict["fullname"]).first()

            if not author:
                author = Author()
                author.fullname = author_dict["fullname"]
                author.born_date = author_dict["born_date"]
                author.born_location = author_dict["born_location"]
                author.description = author_dict["description"]
                author.save()

            saved_authors.update({author.fullname: author})

        for quot_dict in result_dict["quotes"]:

            # db_author = Author.objects.filter(fullname=quot_dict["author"]).first()

            db_author = saved_authors.get(quot_dict["author"])

            print(f"fullname: {quot_dict['author']} class: {db_author}")

            if db_author:

                new_quot = Quot()
                new_quot.author = db_author
                new_quot.quot = quot_dict["quot"]
                new_quot.save()

                for tag_name in quot_dict["tags"]:

                    tag_db = Tag.objects.filter(name=tag_name).first()
                    if not tag_db:
                        new_tag = Tag()
                        new_tag.name = tag_name
                        new_tag.save()
                        tag_db = new_tag

                    new_quot.tags.add(tag_db)

                new_quot.save()

            else:
                print(f"problem author {quot_dict['author']}")

    return redirect(to="quotes_app:main")


def get_most_used_tags():

    sql_query = """CREATE TEMPORARY TABLE temp_table AS
                SELECT 
                  COUNT(1) AS tag_sum, 
                  quot_tags.tag_id as tag_id
                FROM 
                  quotes_app_quot_tags AS quot_tags
                GROUP BY 
                  quot_tags.tag_id
                ORDER BY 
                  tag_sum DESC 
                LIMIT 10;
                
                SELECT temp_table.tag_id AS tag_id,
                    quotes_app_tag.name AS tag_name, 
                    temp_table.tag_sum AS tag_sum
                FROM temp_table
                left join quotes_app_tag on
                temp_table.tag_id = quotes_app_tag.id
                ORDER BY 
                  tag_sum desc,
                  quotes_app_tag.name"""

    with connection.cursor() as cursor:
        cursor.execute(sql_query)

        results = cursor.fetchall()

        column_names = ["tag_id", "tag_name", "tag_sum"]

        list_of_dicts = [dict(zip(column_names, row)) for row in results]

        for dict_ in list_of_dicts:
            dict_["font_size"] = dict_["tag_sum"]*0.16

        return list_of_dicts


def index(request):
    quotes = Quot.objects.all().order_by('creation_date', 'id')
    tag_list = get_most_used_tags()
    return render(request,
                  "quotes_app/index.html",
                  context={"title": "Quotes app main",
                           "quotes": quotes,
                           "quotes_view": False,
                           "tag_list": tag_list})


def author_page(request):
    author_id = request.GET.get('author_id')

    author = Author.objects.filter(id=author_id).first()

    return render(request, "quotes_app/author_page.html", context={"title": "Author page", "author": author})
    # return HttpResponse("Author Page for " + author.fullname)


def tags_search(request):
    tag_id = request.GET.get('tag_id')

    tag = Tag.objects.filter(id=tag_id).first()
    quotes = Quot.objects.filter(tags=tag).all()
    tag_list = get_most_used_tags()

    return render(request,
                  "quotes_app/index.html",
                  context={"title": "Tag search",
                           "quotes": quotes,
                           "quotes_view": True,
                           "tag": tag,
                           "tag_list": tag_list})

    # print(quotes)

    # return render(request, "quotes_app/author_page.html", context={"title": "Author page", "author": author})
    # return HttpResponse(f"tag id {tag} find some qotes {quotes}")


@login_required
def add_author(request):
    if request.method == "POST":

        author_form = AuthorForm(request.POST, instance=Author())

        print(f"USER: {request.user}")
        print(f"author_form.is_valid(): {author_form.is_valid()}")
        print(f"author_form cleaned_data fullname: {author_form.cleaned_data['fullname']}")

        if author_form.is_valid():
            # author_form.save(commit=False)
            authors = Author.objects.filter(fullname=author_form.cleaned_data['fullname']).all()
            if not authors:
                author_form.save()

            return redirect(to="quotes_app:main")

        else:
            print(author_form.errors)

    else:

        author_form = AuthorForm()

        return render(request, "quotes_app/author.html", context={"title": "Author creation", "form": author_form})


@login_required
def add_quot(request):
    if request.method == "POST":

        quot_form = QuotForm(request.POST)

        if quot_form.is_valid():

            quot = quot_form.save(commit=False)
            quot.save()
            tag_names = str(quot_form.cleaned_data["tags"])

            for tag_name in tag_names.split(","):
                tag, _ = Tag.objects.get_or_create(name=tag_name.strip())
                quot.tags.add(tag)

            return redirect(to="quotes_app:main")

        else:
            print(quot_form.errors)

    else:

        quot_form = QuotForm()

        return render(
            request,
            "quotes_app/quot.html",
            context={
                "title": "Quot add",
                "form": quot_form}
        )

# @login_required
# def edit(request, img_id):
#     if request.method == "POST":
#         description = request.POST.get("description")
#         Picture.objects.filter(pk=img_id, user=request.user).update(description=description)
#         return redirect(to="photo_app:pictures")
#
#     pic = Picture.objects.filter(pk=img_id, user=request.user).first()
#     return render(request, "photo_app/change.html", context={"title": "Change description", "pic": pic})

hw10_app/quotes_app/templates/quotes_app/author.html
{% extends 'quotes_app/base.html' %}

{% block content %}
<div class="container mt-3 text-center">
    <h2>Ceate new author</h1>
</div>
<div class="container">
    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form action="{% url 'quotes_app:add_author' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="container mt-3 text-center">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
            <a href="{% url 'quotes_app:main' %}" class="btn btn-success">To main</a>
        </div>
    </form>
    <div class="container mt-3 text-center">
        <a href="{% url 'quotes_app:scrap_data' %}" class="btn btn-success">Make scraping from:
            http://quotes.toscrape.com/</a>
    </div>

</div>
<style>

     .container {
        max-width: 800px;
        margin: 0 auto;
    }


</style>

{% endblock %}

hw10_app/quotes_app/templates/quotes_app/author_page.html
{% extends 'quotes_app/base.html' %}
{% block content %}


<a href="{% url 'quotes_app:main' %}">
    <div class="container mt-3">
        <h1>Quotes to Scrape</h1>
    </div>
</a>

<br>
<br>

<div class="container mt-10 text-left">
    <div class="author-details">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <p>
            <strong>Born:</strong>
            <span class="author-born-date">{{ author.born_date }}</span>
            <span class="author-born-location">{{ author.born_location }}</span>
        </p>
        <p class="text-justify"><strong>Description:</strong></p>
        <div class="author-description container text-justify">
            {{ author.description }}
        </div>
    </div>
</div>


{% endblock %}

hw10_app/quotes_app/templates/quotes_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'photo_app/style.css' %}">
    <title>{{title}}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'quotes_app:main' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes_app:add_author' %}">Add author</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes_app:add_quot' %}">Add quot</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signin' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

hw10_app/quotes_app/templates/quotes_app/index.html
{% extends 'quotes_app/base.html' %}

{% block content %}

<a href="{% url 'quotes_app:main' %}">
    <div class="container mt-3 text-center">
        <h1>Quotes to Scrape</h1>
    </div>
</a>

<div class=" container mt-10 float-end" style="width: 300px;">
    <div class="container mt-10 text-end"><h2>Top ten tags</h2>
        {% for tag_dict in tag_list %}
        <div class="mb-2">
            <a href="{% url 'quotes_app:tags_search' %}?tag_id={{ tag_dict.tag_id }}">
                <button type="button" class="btn btn"
                        style="--bs-btn-padding-x: .13rem; --bs-btn-padding-y: .1rem; --bs-btn-font-size: {{ tag_dict.font_size }}rem; background-color: #87CEFA; color: white;">
                    {{ tag_dict.tag_name }}
                </button>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<style>
    .bg-custom {
        background-color: #87CEFA;
    }









</style>

{% if quotes_view %}
<br>
<div class="container mt-3 text-left">
    <h2>Viewing tag:
        <a href="{% url 'quotes_app:tags_search' %}?tag_id={{ tag.id }}">
            {{ tag }}
        </a>
    </h2>
</div>
{% endif %}

{% for quot in quotes %}

<div class="alert-container">
    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading"><em>{{ quot.quot }}</em></h4>
        <p class="mb-0">by <span>
            <small class="author" itemprop="author">
                <a href="{% url 'quotes_app:author_page' %}?author_id={{ quot.author.id }}">
                    {{ quot.author.fullname }}
                </a>
            </small>
        </span></p>
        <p class="mb-0">
        <div class="tags mt-0 mb-0">
            Tags:
            {% for tag in quot.tags.all %}
            <a href="{% url 'quotes_app:tags_search' %}?tag_id={{ tag.id }}">
                <button type="button" class="btn btn"
                        style="--bs-btn-padding-y: .13rem; --bs-btn-padding-x: .4rem; --bs-btn-font-size: .75rem; background-color: #87CEFA; color: white;">
                    {{ tag.name }}
                </button>
            </a>
            {% endfor %}
        </div>
        </p>
    </div>
</div>
{% endfor %}

<style>

     .container {
        max-width: 800px;
        margin: 0 auto;
    }

    .alert-container {
        max-width: 800px;
        margin: 0 auto;
    }





</style>

<div class="container mt-3">
    <nav aria-label="...">
        <ul class="pagination justify-content-center" style="padding: 10px;">
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

hw10_app/quotes_app/templates/quotes_app/quot.html
{% extends 'quotes_app/base.html' %}

{% block content %}
<div class="container mt-3 text-center">
    <h2>Ceate new quot</h2>
</div>
<div class="container">
    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form action="{% url 'quotes_app:add_quot' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="container mt-3 text-center">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
            <a href="{% url 'quotes_app:main' %}" class="btn btn-success">To main</a>
        </div>
    </form>
    <br>
     <div class="container mt-3 text-center">
        <a href="{% url 'quotes_app:scrap_data' %}" class="btn btn-success">Make scraping from: http://quotes.toscrape.com/</a>
    </div>

</div>
 <style>

     .container {
        max-width: 800px;
        margin: 0 auto;
    }

 </style>
{% endblock %}